version: 2

jobs:
  build:
    working_directory: ~/studego
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: studego-bundler-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: studego-bundler-{{ arch }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: ruby builder.rb > output/output.html
      - store_artifacts:
          path: output/
